# Generated by Django 3.2.7 on 2021-10-30 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_urlsbook_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsbook',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
