# Generated by Django 3.2.7 on 2022-11-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_alter_urlsbook_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsbook',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
