# Generated by Django 3.2.7 on 2022-11-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0004_urlsbook_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlsbook',
            old_name='views',
            new_name='click_counts',
        ),
    ]
